### ISSUE TITLE
What is the difference between run_e3c_double.py and run_e3c.py?

### ISSUE THREAD

**Issue by kasimte** [RunzheYang/MORL#10]
In the `multimario` part of the project, there are the following files:

* run_e3c_double.py
* run_e3c.py

What's the difference between the two?

**Comment by kasimte** [comment]
Ah, I am looking more closely at the code and I see the double file uses `EnveDoubleMoActorAgent`.

**Comment by RunzheYang** [comment]
`run_e3c_double.py ` uses a target critic network to reduce estimation errors, which is similar to [double q-learning](https://arxiv.org/pdf/1509.06461.pdf) and empirically gives better results.

**Comment by kasimte** [comment]
Thanks, @RunzheYang! Very helpful.
