### ISSUE TITLE
Is this a typo or the design of the run_e3c_double.py?

### ISSUE THREAD

**Issue by lesleychou** [RunzheYang/MORL#11]
I noticed on line 245 of `multimario/run_e3c_double.py` reads`rewards.append(fixed_w.dot(mor))`.

Is this supposed to be `explore_w.dot(mor)` like in `run_e3c.py`? Or it's a different design for the algorithm?

Thanks!

**Comment by RunzheYang** [comment]
It is different. `rewards.append(fixed_w.dot(mor))` here is for the plots which monitor the learning progress under some `fixed_w`.  The multi-objective rewards used in the algorithm are on line 248 `morewards.append(mor)`, which should be the same.
