### ISSUE TITLE
What is the purpose of total_utility in run_e3c_double.py?

### ISSUE THREAD

**Issue by kasimte** [RunzheYang/MORL#12]
On line 308 of `run_e3c_double.py`, total_utility is defined as so:

https://github.com/RunzheYang/MORL/blob/9e01c305c2abc9938408de49bb6cea4aca03e44c/multimario/run_e3c_double.py#L308

I couldn't find where it was used, however. What is the purpose of this?

Thanks in advance.

**Comment by RunzheYang** [comment]
Right, `total_utility` seems to be defined but never gets used.
It may be used for the sanity check while debugging...

**Comment by kasimte** [comment]
Thanks for clarifying! I thought I might be missing something.
