### ISSUE TITLE
What is envemask doing inside the envelop_operator()?

### ISSUE THREAD

**Issue by lesleychou** [RunzheYang/MORL#15]
Hi Runzhe, I couldn't understand what did you do with this envelope-mask. Why did you add that np.array here?

https://github.com/RunzheYang/MORL/blob/d8ce3e3ec9475940d346ee1fd5ce0da7bde1d2a7/multimario/run_e3c_double.py#L128

Is the `envemask` related to this part in the pseudo code?
![image](https://user-images.githubusercontent.com/28391838/75034217-189c4480-54f0-11ea-9db0-170419662c6c.png)
why did you choose the w' not w_i inside the value function?

I think this is the core of your algorithm but I am a bit confused TT

**Comment by RunzheYang** [comment]
Yes, lines 126~129 are implementing this part of the algorithm. Using a mask here to select argV makes it fast with gpu. Line 127 reshapes the extended batch in size `(sample_size, -1, ofs)` then picks out all the indices of the second dim with maximum utility under each preference. Then line 128 recovers the indices by shifting them by `0...ofs-1` for `sample_size` times. After these two operations, we have `target[evenmask] = argV`.

We have w' inside the value function and wi outside the value function, which means for each preference wi, we are looking for the best achievable V giving highest utility. This allows the algorithm to quickly align one preference with optimal rewards and trajectories that may have been explored under other preferences. This is like solving the convex envelope of the value frontier. You can check Fig. 2(c) and the paragraph below theorem 3 in the paper.
