### ISSUE TITLE
What is the difference between envelope, energy and naive?

### ISSUE THREAD

**Issue by thisishale** [RunzheYang/MORL#17]
Envelope is the main paper's approach. However, I do not understand what energy and naive means in the code. Are they baselines (Q fitted iteration and scalarized)?

**Comment by RunzheYang** [comment]
'envelope' is the main algorithm, 'naive' is the scalarized baseline. 'energy' is an energy-based policy extension for continous action space which is not presented in the paper.

**Comment by thisishale** [comment]
Thank you. How about envelope_old? 
Also, the eval_ft code prints policy and prediction results for F1 (coverage ratio). 
Are the F1 results for fruit tree navigation task in the paper the policy F1 or the prediction F1?

**Comment by RunzheYang** [comment]
Please ignore _old folders. I believe they are some heritages unrelated to the paper.. The F1 scores reported in paper are policy F1 scores.
