### ISSUE TITLE
The operation of synthetic/crl/envelope/meta.py

### ISSUE THREAD

**Issue by mununum** [RunzheYang/MORL#18]
Hello,

I am trying to read the MORL paper and your code.

I'm currently looking at synthetic/crl/envelope/meta.py,
but in learn() function, it seems to the H() operator is implemented differently from your paper.

https://github.com/RunzheYang/MORL/blob/68602002057762f0c5f318ecb9dddf36d0cc91ab/synthetic/crl/envelope/meta.py#L190-L206

In the above code, it just takes an inner product of w_ext and tmpQ, then argmax over actions, like the equation below.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/15724122/98331312-a9e02680-203f-11eb-8e04-0bded1068544.png">

I think it behaves differently from the paper, which is described as

<img width="654" alt="image" src="https://user-images.githubusercontent.com/15724122/98331214-73a2a700-203f-11eb-9678-1230f373bee9.png">

Actually, I see the commented line 191~192 in your code, and they seem to behave consistently with your paper.
It seems that you intentionally commented it out and made a new version, for some purpose.

Could you explain why you did this? Thanks!

**Comment by RunzheYang** [comment]
Sorry I don’t remember as it’s been long ago. But I think the envelope `H()` should be the `H()` implemented in the model.

**Comment by mununum** [comment]
Then the `H()` in the model (which in this case the commented line) should be used as a target.
I looked carefully at your code multiple times and also looked the A3C version in multimario code,
but the `H()` operator in the code just takes the same preference vector for both value calculation and scalarization.
This does not make sense since your paper claims that your algorithm can utilize the off-preference samples to update the envelope.
Sorry for bothering you with your work from long time ago. But to me the latest code seems like it is updating the envelope in preference-by-preference manner, rather than like the way described in the paper.
I guess it could be the computational issue...

**Comment by RunzheYang** [comment]
Hi @mununum, thanks for asking. I think the envelope `H()` is also explained in #15. The update uses the same set of update preferences for value calculation and scalarization, and the max is taken over all these update preferences for each scalarization preference. This is the "utilizing the off-preference samples" claim in the paper as they are not aligned. The envelope calculation is within a preference x preference batch as described in the paper. Please let me know if this addresses your questions...  
Also, if it's more convenient for you as well, I'd be happy to schedule a call to have a conversation about the paper sometime. Please feel free to email me. And we can go back and summarize code related issues here.

**Comment by mununum** [comment]
Hi, thanks for the active reply!

> The update uses the same set of update preferences for value calculation and scalarization, and the max is taken over all these update preferences for each scalarization preference.

I understand the same batch of random preference vectors are used, but the "max is taken over all these update preferences" explanation doesn't seem to align with the following code, which takes an argmax over "actions".

https://github.com/RunzheYang/MORL/blob/68602002057762f0c5f318ecb9dddf36d0cc91ab/synthetic/crl/envelope/meta.py#L203-L204

(I believe it's a code-related issue, since we are talking about the operation of the code)

https://github.com/RunzheYang/MORL/blob/68602002057762f0c5f318ecb9dddf36d0cc91ab/synthetic/crl/envelope/models/linear.py#L39-L65

I think this part of the code makes sense as it takes the argmax over (action_size x w_num), but this function call is commented out in the master branch.

Please tell me if I'm understanding anything incorrectly, thanks!

**Comment by anirjoshi** [comment]
Hi @mununum @RunzheYang, I believe this issue still persists in the codebase. How was it resolved?
