### ISSUE TITLE
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray

### ISSUE THREAD

**Issue by kasimte** [RunzheYang/MORL#8]
@RunzheYang: Any chance you saw this error when running the evaluation script for the FTN environment?

```
Traceback (most recent call last):
  File "test/eval_ft.py", line 387, in <module>
    qc = hq.data[0] * w_e
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```

It looks like it isn't affecting the pareto frontier plots and could also be fixed by just converting the numpy array to a pytorch tensor, but I'm wondering if has to do with my environment setup.

**Comment by RunzheYang** [comment]
Ah yes, this is because of the PyTorch version. 
Are you using PyTorch 0.4.0?
If so I am going to accept your merge.

**Comment by kasimte** [comment]
Ah, thank you for the note! I'm pretty sure I was on a higher version of PyTorch at the time.
